{{/* vim: set filetype=mustache: */}}

# Annotation Generators
{{- define "chronicle.pod.annotations" -}}
{{- range $key,$value := $.Values.pod.annotations -}}
{{ $key }}: {{ $value | quote }}
{{ end }}
{{- if .Values.config.metrics.enabled }}
prometheus.io/scrape: "true"
prometheus.io/port: "{{ .Values.pod.rest.port }}"
{{- end }}
{{- end -}}

{{- define "chronicle.serviceaccount.annotations" -}}
{{- range $key,$value := $.Values.serviceaccount.annotations -}}
{{ $key }}: {{ $value | quote }}
{{ end }}
{{- end -}}

{{- define "chronicle.service.annotations" -}}
{{- range $key,$value := $.Values.service.annotations -}}
{{ $key }}: {{ $value | quote }}
{{ end }}
{{- end -}}
