project: 
  type: posit-docs
  pre-render: |
    ./helm-docs --chart-search-root=charts --template-files=README.md.gotmpl --template-files=./_templates.gotmpl
    ./helm-docs --chart-search-root=other-charts --template-files=README.md.gotmpl --template-files=./_templates.gotmpl
  render: 
    - charts/rstudio-workbench/README.md 
    - charts/rstudio-workbench/NEWS.md 
    - charts/rstudio-connect/README.md
    - charts/rstudio-connect/NEWS.md
    - charts/rstudio-pm/README.md
    - charts/rstudio-pm/NEWS.md
    - charts/posit-chronicle/README.md
    - charts/posit-chronicle/NEWS.md
    - examples/auto-scaling/README.md
    - examples/rbac/README.md
    - examples/workbench/README.md
    - examples/connect/README.md
    - docs/customize.md
    - "*.qmd"

filters:
  - include-code-files

website: 
  title: Posit Helm Charts
  site-url: https://docs.posit.co/helm
  bread-crumbs: true
  repo-url: https://github.com/rstudio/helm
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Copyright &copy; 2000-{{< env CURRENT_YEAR >}} Posit Software, PBC. All Rights Reserved.
    center: |
      Posit Helm Charts {{< env PRODUCT_VERSION >}}
    right:
      - icon: question-circle-fill
        href: "https://support.posit.co/hc/en-us"
      - icon: lightbulb-fill
        href: "https://solutions.posit.co/"
      - text: "<img src='/images/posit-guide-ltmd.svg' id='footer-right-logo'>"
        href: "https://docs.posit.co/"
      - text: "<img src='/images/posit-logo-black-TM.svg' id='footer-right-posit-logo'>"
        href: "https://posit.co/"
  navbar:
    right:
      - icon: "list"
        menu:
          - text: "docs.posit.co"
            href: "https://docs.posit.co"
          - text: "Posit Support"
            href: "https://support.posit.co/hc/en-us/"
  sidebar:
    style: "floating"
    collapse-level: 1
    search: true
    pinned: false
    contents:
      - text: Overview
        file: index.qmd
      - section: "Posit Workbench"
        contents:
          - text: Overview
            file: charts/rstudio-workbench/README.md
          - text: Changelog
            file: charts/rstudio-workbench/NEWS.md
          - text: Examples
            file: examples/workbench/index.qmd

      - section: "Posit Connect"
        contents:
          - text: Overview
            file: charts/rstudio-connect/README.md
          - text: Changelog
            file: charts/rstudio-connect/NEWS.md
          - text: Examples
            file: examples/connect/index.qmd
      - section: "Posit Package Manager"
        contents:
          - text: Overview
            file: charts/rstudio-pm/README.md
          - text: Changelog
            file: charts/rstudio-pm/NEWS.md
          - text: Examples
            file: examples/package-manager/index.qmd
      - section: "Posit Chronicle"
        contents:
          - text: Overview
            file: charts/posit-chronicle/README.md
          - text: Changelog
            file: charts/posit-chronicle/NEWS.md
