---
# Source: prepull-daemonset/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull-daemonset
  labels:
    app: prepull-daemonset
spec:
  selector:
    matchLabels:
      name: prepull-daemonset
  template:
    metadata:
      annotations:
        rollme: "I7c6YhiL9E"
      labels:
        name: prepull-daemonset
    spec:
      initContainers:
        - name: prepull-prepull-image
          image: rstudio/r-session-complete:bionic-1.3.1093-1
          imagePullPolicy: Always
          command: ["echo"]
          args: ["Finished pre-pull"]
      containers:
        - name: pause
          image: gcr.io/google_containers/pause
