---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-prestart
  namespace: {{ $.Release.Namespace }}
data:
  prestart-workbench.bash: |
    {{- .Files.Get "prestart-workbench.bash" | nindent 4 }}
  prestart-launcher.bash: |
    {{- .Files.Get "prestart-launcher.bash" | nindent 4 }}
