{{- if .Values.sealedSecret.enabled -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    {{- tpl ( toYaml .Values.sealedSecret.annotations ) . | nindent 4 }}
  name: {{ include "rstudio-workbench.fullname" . }}-secret
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    {{- include "rstudio-library.config.ini" .Values.config.secret | nindent 4 }}
    launcher.pem: |
      {{- include "rstudio-workbench.launcherPem" . | nindent 6 }}
    secure-cookie-key: |
      {{- include "rstudio-workbench.secureCookieKey" . | nindent 6 }}
  template:
    data:
      {{- if .Values.launcherPub }}
      # TODO: would ideally be able to generate launcher.pub as well
      launcher.pub: |
        {{- .Values.launcherPub | nindent 10 }}
      {{- end }}
---
{{- if .Values.config.userProvisioning }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    {{- tpl ( toYaml .Values.sealedSecret.annotations ) . | nindent 4 }}
  name: {{ include "rstudio-workbench.fullname" . }}-user
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    {{- include "rstudio-library.config.ini" .Values.config.userProvisioning | nindent 4 }}
{{- end }}
{{- end }}
