apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-start-rsw
  namespace: {{ $.Release.Namespace }}
data:
  rstudio-workbench.conf: |
    [program:rstudio-workbench]
    command=/scripts/prestart-workbench.bash /usr/local/bin/startup.sh
    autorestart=false
    numprocs=1
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
{{- if .Values.launcher.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-start-launcher
  namespace: {{ $.Release.Namespace }}
data:
  rstudio-launcher.conf: |
    [program:rstudio-launcher]
    command=/scripts/prestart-launcher.bash /usr/lib/rstudio-server/bin/rstudio-launcher
    autorestart=false
    numprocs=1
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
{{- end }}
{{- if .Values.config.userProvisioning }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-start-user
  namespace: {{ $.Release.Namespace }}
data:
  sssd.conf: |
    [program:sssd]
    command=/usr/sbin/sssd -i -c /etc/sssd/sssd.conf --logger=stderr
    autorestart=false
    numprocs=1
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stdout_logfile_backups=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    stderr_logfile_backups=0
{{- end }}
{{- if .Values.config.startup }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-start-custom
  namespace: {{ $.Release.Namespace }}
data:
  {{- include "rstudio-library.config.ini" .Values.config.startup | nindent 2}}
{{- end }}
