{{- if .Values.rbac.create }}
{{- $namespace := $.Release.Namespace }}
{{- $targetNamespace := default $.Release.Namespace .Values.launcher.namespace }}
{{- $serviceAccountName := default (include "rstudio-workbench.fullname" .) .Values.rbac.serviceAccount.name }}
{{- $serviceAccountCreate := .Values.rbac.serviceAccount.create }}
{{- $roleName := $serviceAccountName }}
{{- $serviceAccountAnnotations := .Values.rbac.serviceAccount.annotations }}
{{- $serviceAccountLabels := .Values.rbac.serviceAccount.labels }}
{{- $clusterRoleCreate := .Values.rbac.clusterRoleCreate }}
{{- $rbacValues1 := dict "namespace" $namespace "serviceAccountName" $serviceAccountName "targetNamespace" $targetNamespace }}
{{- $rbacValues2 := dict "serviceAccountCreate" $serviceAccountCreate "serviceAccountAnnotations" $serviceAccountAnnotations "serviceAccountLabels" $serviceAccountLabels "roleName" ($roleName) }}
{{- $rbacValues3 := dict "clusterRoleCreate" $clusterRoleCreate }}
{{- $rbacValues := merge $rbacValues1 $rbacValues2 $rbacValues3 }}
{{- include "rstudio-library.rbac" $rbacValues }}
{{- end }}
