apiVersion: v2
name: posit-chronicle
description: Helm chart for the Chronicle Server
version: 0.1.0
appVersion: 2023.11.0
icon: https://rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-Flat.png
home: https://www.posit.co
sources:
  - https://github.com/rstudio/helm
maintainers:
  - name: sol-eng
    email: docker@rstudio.com
    url: https://github.com/rstudio/helm
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Posit Community
      url: https://community.rstudio.com/c/r-admin/5
    - name: About Posit Team
      url: https://posit.co/products/enterprise/team/
keywords:
  - "rstudio"
  - "chronicle"
