image:
  repository: rstudio/rstudio-package-manager
  tag: 1.1.6.1-5
  imagePullPolicy: Always
  imagePullSecrets:
    - name: "some-secret"
license:
  key: test
service:
  type: NodePort
  annotations:
    key: value
    key2: value2
  nodePort: 32420
replicas: 1
config:
  HTTP:
    Listen: :4242
  Server:
    DataDir: /var/lib/rstudio-pm
    RVersion:
      - /opt/R/3.6.2
  Git:
    BuilderDir: "/tmp/git"
rstudioPMKey: somevalue
awsAccessKeyId: keyid
awsSecretAccessKey: keysecret
storageClaim: someClaimName

command: '["sleep","1000"]'
args: '[]'

initContainers:
  - name: busybox
    image: busybox
    command: ["echo"]
    args: ["init"]
