---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rstudio-pm.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "rstudio-pm.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rstudio-pm.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    name: rspm
    port: {{ .Values.service.port }}
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    targetPort: 4242
{{- if .Values.config.Metrics.Enabled }}
  - name: metrics
    port: 2112
{{- end }}
---
