name: Kubernetes
images:
  -
    name: ghcr.io/rstudio/content-pro:r3.6.3-py3.8.19-ubuntu2204
    python:
      installations:
        -
          path: /opt/python/3.8.19/bin/python3
          version: 3.8.19
    r:
      installations:
        -
          path: /opt/R/3.6.3/bin/R
          version: 3.6.3
    quarto:
      installations:
        - path: /opt/quarto/1.3.450/bin/quarto
          version: 1.3.450
  -
    name: ghcr.io/rstudio/content-pro:r4.0.5-py3.9.19-ubuntu2204
    python:
      installations:
        -
          path: /opt/python/3.9.19/bin/python3
          version: 3.9.19
    r:
      installations:
        -
          path: /opt/R/4.0.5/bin/R
          version: 4.0.5
    quarto:
      installations:
        - path: /opt/quarto/1.3.450/bin/quarto
          version: 1.3.450
  -
    name: ghcr.io/rstudio/content-pro:r4.1.3-py3.10.14-ubuntu2204
    python:
      installations:
        -
          path: /opt/python/3.10.14/bin/python3
          version: 3.10.14
    r:
      installations:
        -
          path: /opt/R/4.1.3/bin/R
          version: 4.1.3
    quarto:
      installations:
        - path: /opt/quarto/1.3.450/bin/quarto
          version: 1.3.450
  -
    name: ghcr.io/rstudio/content-pro:r4.2.3-py3.11.9-ubuntu2204
    python:
      installations:
        -
          path: /opt/python/3.11.9/bin/python3
          version: 3.11.9
    r:
      installations:
        -
          path: /opt/R/4.2.3/bin/R
          version: 4.2.3
    quarto:
      installations:
        - path: /opt/quarto/1.3.450/bin/quarto
          version: 1.3.450
  -
    name: ghcr.io/rstudio/content-pro:r4.3.3-py3.12.3-ubuntu2204
    python:
      installations:
        -
          path: /opt/python/3.12.3/bin/python3
          version: 3.12.3
    r:
      installations:
        -
          path: /opt/R/4.3.3/bin/R
          version: 4.3.3
    quarto:
      installations:
        - path: /opt/quarto/1.4.553/bin/quarto
          version: 1.4.553
  -
    name: ghcr.io/rstudio/content-pro:r4.4.0-py3.12.3-ubuntu2204
    python:
      installations:
        -
          path: /opt/python/3.12.3/bin/python3
          version: 3.12.3
    r:
      installations:
        -
          path: /opt/R/4.4.0/bin/R
          version: 4.4.0
    quarto:
      installations:
        - path: /opt/quarto/1.4.553/bin/quarto
          version: 1.4.553
