{{- if .Values.sharedStorage.create }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{default (print (include "rstudio-connect.fullname" .) "-shared-storage" ) .Values.sharedStorage.name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- .Values.sharedStorage.annotations | toYaml | nindent 4 }}
spec:
  accessModes:
{{ .Values.sharedStorage.accessModes | toYaml | indent 4 }}
  volumeMode: Filesystem
  {{- if .Values.sharedStorage.storageClassName }}
  storageClassName: {{ .Values.sharedStorage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sharedStorage.requests.storage }}
---
{{- end }}
