---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chronicle-server
  namespace: {{ $.Release.Namespace }}
spec:
  serviceName: chronicle-server
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "posit-chronicle.pod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "posit-chronicle.pod.labels" . | nindent 8 }}
        {{- include "posit-chronicle.pod.selectorLabels" . | indent 8 }}
      annotations:
        {{- include "posit-chronicle.pod.annotations" . | indent 8 }}
    spec:
      {{- with .Values.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceaccount.enabled }}
      serviceAccountName: chronicle-sa
      {{- end }}
      containers:
      - name: chronicle-server
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command: 
        - {{ .Values.pod.command }}
        {{- if .Values.pod.args }}
        args:
        {{- toYaml .Values.pod.args | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.pod.rest.port }}
          name: tcp
        volumeMounts:
        - name: data
          mountPath: {{ .Values.config.localStorage.location }}
        - name: chronicle-server-config
          mountPath: /opt/chronicle/config.gcfg
          subPath: server
        {{- if .Values.pod.env }}
        env: 
        {{- toYaml .Values.pod.env | nindent 8 }}
        {{- end }}
      volumes:
      - name: chronicle-server-config
        configMap:
          name: chronicle-server-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage.persistentVolumeSize }}
---
