# defaults to chart `appVersion`
versionOverride: ""

launcher:
  enabled: true
  templateValues:
    imagePullSecrets:
      - my-regcred
  defaultInitContainer:
    repository: my-org/rstudio-connect-content-init
    # defaults to chart `appVersion` or `versionOverride`
    tag: ""
image:
  repository: my-org/rstudio-connect
  # defaults to chart `appVersion` or `versionOverride`
  tag: ""
  imagePullSecrets:
    - my-regcred

sharedStorage:
  create: true
  storageClassName: my-nfs-storage-class

securityContext: null

config:
  Database:
    Provider: postgres
  Postgres:
    URL: postgres://user@some-url.com:5432/rsc?sslmode=disable
    Password: my-password
