name: Document Charts

on:
  pull_request:

jobs:
  document:
    runs-on: ubuntu-latest
    name: helm-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - name: Install helm-docs
        env:
          version: 1.5.0
        run: |
          echo "Installing helm-docs version $version"
          curl -L -o helm-docs.tar.gz https://github.com/norwoodj/helm-docs/releases/download/v${version}/helm-docs_${version}_Linux_x86_64.tar.gz
          tar -xzvf helm-docs.tar.gz helm-docs
          rm -rf helm-docs.tar.gz

      - name: Run helm-docs
        run: |
          ./helm-docs --chart-search-root=charts --template-files=README.md.gotmpl --template-files=./_templates.gotmpl
          ./helm-docs --chart-search-root=other-charts --template-files=README.md.gotmpl --template-files=./_templates.gotmpl

      - name: Commit results
        run: |
          set -xe
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit other-charts/*/README.md charts/*/README.md -m 'Update helm-docs and README.md' || echo "No changes to commit"

      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  rbac:
    runs-on: ubuntu-latest
    name: rbac
    needs: document
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - name: Compute and update dependent files
        run: |
          set -xe
          cd ./charts/rstudio-launcher-rbac && helm dependency build && cd -
          helm template -n rstudio rstudio-launcher-rbac ./charts/rstudio-launcher-rbac --set removeNamespaceReferences=true > examples/rbac/rstudio-launcher-rbac.yaml
          CHART_VERSION=$(helm show chart ./charts/rstudio-launcher-rbac | grep '^version' | cut -d ' ' -f 2)
          cp examples/rbac/rstudio-launcher-rbac.yaml examples/rbac/rstudio-launcher-rbac-${CHART_VERSION}.yaml

      - name: Commit results
        run: |
          set -xeo pipefail
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add examples/rbac/rstudio-launcher-rbac*.yaml || echo "No files to add"
          git commit examples/rbac/rstudio-launcher-rbac*.yaml -m 'Update rbac yaml' || echo "No changes to commit"

      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
