name: Lint and Test Charts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main --chart-dirs charts --chart-dirs other-charts)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint changed)
        run: ct lint --target-branch main --chart-dirs charts --chart-dirs other-charts

      - name: Run chart-testing (lint all)
        run: ct lint --target-branch main --all --chart-dirs charts --chart-dirs other-charts

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main --chart-dirs charts --chart-dirs other-charts)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Create kind cluster
        uses: helm/kind-action@v1.1.0
        if: ( steps.list-changed.outputs.changed == 'true' ) || ${{ github.ref == 'refs/heads/main' }}

      # no allow-failure until https://github.com/actions/toolkit/issues/399
      - name: Run chart-testing (install changed)
        if: ${{ github.ref != 'refs/heads/main' }}
        run: ct install --target-branch main --chart-dirs charts --chart-dirs other-charts
        continue-on-error: true

      # no allow-failure until https://github.com/actions/toolkit/issues/399
      - name: Run chart-testing (install all)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ct install --target-branch main --all --chart-dirs charts --chart-dirs other-charts
        continue-on-error: true
