name: Quarto Publish to docs.posit.co

on:
  workflow_dispatch:
  push:
    branches: main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check out repository
        uses: actions/checkout@v4

      - name: install Just
        uses: extractions/setup-just@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
          
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
      
      - run: just push-docs

